theme: minima
title: "Your Blog Title"
description: "A blog powered by GitHub Pages and OpenAI"
baseurl: "/research_blogger"
url: "https://porkpy.github.io"
permalink: /:year/:month/:day/:title/
future: true
