theme: minima
title: "AI Research Blog"
description: "A blog powered by GitHub Pages and the OpenAI api"
baseurl: "/research_blogger"
url: "https://porkpy.github.io"
permalink: /:year/:month/:day/:title/
future: true
